# Generated by Django 5.1.3 on 2024-12-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('tipo_categoria', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField()),
                ('estado_categoria', models.CharField(max_length=50)),
                ('productos_asociados', models.CharField(max_length=300)),
            ],
        ),
    ]
