# Generated by Django 5.1.3 on 2024-12-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('id_cliente', models.PositiveIntegerField()),
                ('fecha_pedido', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=50)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('direccion_envio', models.CharField(max_length=200)),
            ],
        ),
    ]
